spring:
  application:
    name: songlist-service
  cloud:
    config:
      uri: http://localhost:8888


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}




