spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}




